### ISSUE TITLE
Feature request: MultiGPU

### ISSUE THREAD

**Issue by jamilbk** [plaidml/plaidbench#13]
Hi there,

Thanks for providing such an easy to use cross platform ML benchmark!

I see [what appears to be MultiGPU support in PlaidML](https://github.com/plaidml/plaidml/blob/master/plaidml/__init__.py#L947) but are there plans to support this in plaidbench?

System:
- Gigabyte X399
- Threadripper 1950X
- 4x Vege FE
- PlaidML version 0.1.0rc3

```
jamil@fridge:~/dl/plaidbench (master=) % python plaidbench.py --print-stacktraces mobilenet 
Using PlaidML backend.
INFO:plaidml:Initializing device gfx900.0: "gfx900", vendor "Advanced Micro Devices, Inc."
INFO:plaidml:Initializing device gfx900.1: "gfx900", vendor "Advanced Micro Devices, Inc."
INFO:plaidml:Initializing device gfx900.2: "gfx900", vendor "Advanced Micro Devices, Inc."
INFO:plaidml:Initializing device gfx900.3: "gfx900", vendor "Advanced Micro Devices, Inc."
Too many devices configured. Please run plaidml-setup.
Traceback (most recent call last):
  File "plaidbench.py", line 208, in <module>
    main()
  File "plaidbench.py", line 135, in main
    model = globals['build_model']()
  File "/home/jamil/dl/plaidbench/networks/mobilenet.py", line 30, in build_model
    model = kapp.mobilenet.MobileNet()
  File "/usr/local/lib/python2.7/dist-packages/keras/applications/mobilenet.py", line 449, in MobileNet
    x = _conv_block(img_input, 32, alpha, strides=(2, 2))
  File "/usr/local/lib/python2.7/dist-packages/keras/applications/mobilenet.py", line 586, in _conv_block
    name='conv1')(inputs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 575, in __call__
    self.build(input_shapes[0])
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 134, in build
    constraint=self.kernel_constraint)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 396, in add_weight
    weight = K.variable(initializer(shape),
  File "/usr/local/lib/python2.7/dist-packages/keras/initializers.py", line 212, in __call__
    dtype=dtype, seed=self.seed)
  File "/usr/local/lib/python2.7/dist-packages/plaidml/keras/backend.py", line 2033, in random_uniform
    rng_state = _make_rng_state(seed)
  File "/usr/local/lib/python2.7/dist-packages/plaidml/keras/backend.py", line 927, in _make_rng_state
    rng_state = variable(rng_init, dtype='uint32')
  File "/usr/local/lib/python2.7/dist-packages/plaidml/keras/backend.py", line 2330, in variable
    tensor = plaidml.Tensor(_device(), plaidml.Shape(_ctx, _dtypes[dtype], *value.shape))
  File "/usr/local/lib/python2.7/dist-packages/plaidml/keras/backend.py", line 86, in _device
    devices = plaidml.devices(_ctx)
  File "/usr/local/lib/python2.7/dist-packages/plaidml/__init__.py", line 960, in devices
    raise exceptions.PlaidMLError("Too many devices configured. Please run plaidml-setup.")
plaidml.exceptions.PlaidMLError: Too many devices configured. Please run plaidml-setup.
```

```
jamil@fridge:~/dl/plaidbench (master=) % cat ~/.plaidml 
{
    "PLAIDML_DEVICE_IDS":[
        "gfx900.0",
        "gfx900.1",
        "gfx900.2",
        "gfx900.3"
    ],
    "PLAIDML_EXPERIMENTAL":true,
    "PLAIDML_TELEMETRY":true
}
```

**Comment by jamilbk** [comment]
Ahh nvmd, looks like this is planned for PlaidML:

https://github.com/plaidml/plaidml/issues/31
https://github.com/plaidml/plaidml/issues/32

**Comment by brianretford** [comment]
Sadly we don't have formal support multiple devices yet, and Keras has no provisions for handling multiple devices outside of what its backends provide. There are multiple ways this could be handled, I've documented them in PlaidML

**Comment by deacix** [comment]
Hi every one! What is the state? Do you support multiple devices?
