### ISSUE TITLE
Windows related erorrs maybe?

### ISSUE THREAD

**Issue by Mandrewoid** [plaidml/plaidbench#30]
Downloading data fails in plaidbench.py on Windows. 
First I want to say I'm SUPER STOKED about this product in all ways. I've been looking for something to run GPU acceleration on my AMD GPU for almost an entire year now.

The good: 
Install was super easy,  mobilenet runs and cuts execution time from ~50 seconds (tensorflow) to ~5seconds (compile) ~3 (execute) on a Radeon HD 7950 
That's a 7 year old GPU! and on Windows to boot! Can't express how amazing that is.

The bad: 
The examples that require downloading additional data don't finish the downloads. They stop at around 20% with an ETA of 1s and just hangs until the remote host closes the connection. Tried in git bash, powershell, and command prompt. When you forcibly quit and try again, it says:

A local file was found, but it seems to be incomplete or outdated because the md5 file hash does not match the original value of 9a0d58056eeedaa3f26cb7ebd46da564 so we will re-download the data.

It doesn't say where this local file was found, or what it is called. This seems like there is an easy fix available, to have me download the data manually and put it where it is expected, but I don't know where that is.

The also bad:
mobilenet training doesn't seem to use GPU at all. With batch sizes 1,2 and 4 the GPU usage stays at 0 for the duration of the training.  With batch sizes of > 4 I get:

Compiling and running initial batch, batch_size=8
INFO:plaidml:b'Analyzing Ops: 1104 of 2386 operations complete'
Epoch 1/1
ERROR:plaidml:b'unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE'
exception: access violation writing 0x0000000000000030

Again thanks so much for all the work you've done so far. I'll do my best to contribute in any way I can.

**Comment by earhart** [comment]
Hi -- thanks for the feedback!

I'm not sure whether that GPU uses synchronous or asynchronous command queuing with OpenCL, but if it's seven years old, it's likely synchronous.  I've been experimenting with some ways to improve memory usage on synchronous devices without taking a performance hit; I might have something ready to go soon.  In any event, we shouldn't be seeing access violations when we do run out of GPU memory; I'll see if I can reproduce & fix that.

(It's not a complete fix; to really do the right thing for large networks, we'd need to dynamically swap memory back to the host system when it's not being used by the GPU.  The underlying functionality to do it is all written, but implementing the scheduler changes to figure out when to do it is a little trickier.)

PlaidBench uses Keras for downloading data files and executing models.  On my machine, I don't have a `.keras` directory in `%USERPROFILE%`, so Keras is using `C:\tmp\.keras` for its working directory.  I can try to reproduce the downloading error (although fixing it on the Keras side might be a little tricky).  Which network are you seeing the problem with?

**Comment by Mandrewoid** [comment]
Thanks for getting back to me! The GCN architecture in the AMD 7xx0 series is the same as the r9 2xx and  3xx series. According to this review from 2012 it has async compute http://www.guru3d.com/articles-pages/his-radeon-hd-7950-review,5.html But I don't know enough about OpenCL to know if that's being used to its full potential. 
As far as the downloading error, it's happening on all the networks that require downloading that I've tried.

**Comment by brianretford** [comment]
When you ran plaidml-setup -- did you pick the GPU? I'll also note that mobilenet was designed for CPUs and it doesn't do great on GPUs without reasonable batch sizes. Can you dump the contents of `cat ~/.plaidml'?

**Comment by Mandrewoid** [comment]
@brianretford Yes I picked the GPU. 
{
    "PLAIDML_EXPERIMENTAL":true,
    "PLAIDML_TELEMETRY":true
}

**Comment by Mandrewoid** [comment]
Update. some good and bad news.
 good news:
Downloaded the dataset manually. I'll have to talk to some keras people about why it won't download. 
python plaidbench.py vgg19 now executes properly, with a decent speedup over CPU only. 

Bad news: Training fails. with 
ERROR:plaidml:b'unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE'
python plaidbench.py vgg19 --train --print-stacktraces
Traceback (most recent call last):
  File "plaidbench.py", line 362, in <module>
    main()
  File "plaidbench.py", line 291, in main
    compile_stop_watch, epochs, stop_watch, output, network)
  File "plaidbench.py", line 107, in train
    model.train_on_batch(x_train[0:batch_size], y_train[0:batch_size])
  File "C:\Python36\lib\site-packages\keras\engine\training.py", line 1762, in train_on_batch
    outputs = self.train_function(ins)
  File "C:\Python36\lib\site-packages\plaidml\keras\backend.py", line 966, in __call__
    self._invoker.invoke()
  File "C:\Python36\lib\site-packages\plaidml\__init__.py", line 1397, in invoke
    return Invocation(self._ctx, self)
  File "C:\Python36\lib\site-packages\plaidml\__init__.py", line 1403, in __init__
    self._as_parameter_ = _lib().plaidml_schedule_invocation(ctx, invoker)
OSError: exception: access violation writing 0x0000000000000030

Incedental: The debug messages are b'' strings, why?

**Comment by brianretford** [comment]
Are you running 0.1.6? We released it recently and it improves memory
pressure somewhat. In general though you'll always eventually run out of
memory on any card if the batch size is too high - though the default is 1.
You might try running plaidbench with --blanket to see which networks and
batch sizes are successful and which ones don't work. We know we have a lot
of work to do to improve training performance. We have a few other large
tasks before we get to that.

Re: debug messages, because they were wrapped by hand using ctypes from our
c++ libraries and we're all still getting used to this Python 3 thing.
Patches welcome :-)

**Comment by Mandrewoid** [comment]
Thanks @brianretford I was running 0.1.5. Ran pip install plaidml --upgrade now I'm at 0.1.6
Unfortuately now everything is broken. Here's the traceback:

C:\Python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtyp
e from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).t
ype`.                                                                                                           
  from ._conv import register_converters as _register_converters                                                
Traceback (most recent call last):                                                                              
  File "plaidbench.py", line 362, in <module>                                                                   
    main()                                                                                                      
  File "plaidbench.py", line 224, in main                                                                       
    plaidml.keras.install_backend()                                                                             
  File "C:\Python36\lib\site-packages\plaidml\keras\__init__.py", line 72, in install_backend                   
    from keras.utils import conv_utils                                                                          
  File "C:\Python36\lib\site-packages\keras\__init__.py", line 3, in <module>                                   
    from . import utils                                                                                         
  File "C:\Python36\lib\site-packages\keras\utils\__init__.py", line 6, in <module>                             
    from . import conv_utils                                                                                    
  File "C:\Python36\lib\site-packages\keras\utils\conv_utils.py", line 3, in <module>                           
    from .. import backend as K                                                                                 
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load                                             
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked                                    
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked                                             
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible                                  
  File "C:\Python36\lib\site-packages\plaidml\keras\__init__.py", line 99, in load_module                       
    self._add_imports(mod, self._backend_modname)                                                               
  File "C:\Python36\lib\site-packages\plaidml\keras\__init__.py", line 109, in _add_imports                     
    impl = importlib.import_module(import_modname, __name__)                                                    
  File "C:\Python36\lib\importlib\__init__.py", line 126, in import_module                                      
    return _bootstrap._gcd_import(name[level:], package, level)                                                 
  File "C:\Python36\lib\site-packages\plaidml\keras\backend.py", line 54, in <module>                           
    'float16': plaidml.DATA_FLOAT16,                                                                            
AttributeError: 'Module' object has no attribute 'DATA_FLOAT16'

**Comment by Mandrewoid** [comment]
It seems like DATA_XXXX has been moved into a different namespace? Plaidml.DType but is still being called in the backend.py file. I'll see what I can do about it, but that seems like a pretty serious problem? Did something else change that didn't get updated for me when I upgraded?

**Comment by brianretford** [comment]
Ah, you need to run `pip install -U plaidml-keras` -- the interface changed

**Comment by Mandrewoid** [comment]
So I got time to try with the update, unfortunately no better.
C:\Users\Andrew\plaidbench>python plaidbench.py vgg19 --train --print-stacktraces
Using PlaidML backend.
C:\Python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

Current network being run : vgg19
Running 1024 examples with vgg19, batch size 1
Loading the data
INFO:plaidml:b'Opening device "tahiti.0"'
Model loaded.
Compiling and running initial batch, batch_size=1
INFO:plaidml:b'Analyzing Ops: 48 of 570 operations complete'
INFO:plaidml:b'Analyzing Ops: 113 of 570 operations complete'
INFO:plaidml:b'Analyzing Ops: 230 of 570 operations complete'
INFO:plaidml:b'Analyzing Ops: 249 of 570 operations complete'
INFO:plaidml:b'Analyzing Ops: 261 of 570 operations complete'
INFO:plaidml:b'Analyzing Ops: 274 of 570 operations complete'
INFO:plaidml:b'Analyzing Ops: 286 of 570 operations complete'
INFO:plaidml:b'Analyzing Ops: 299 of 570 operations complete'
INFO:plaidml:b'Analyzing Ops: 305 of 570 operations complete'
WARNING:plaidml:b'Reached scheduler optimization timeout'
ERROR:plaidml:b'unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE'
exception: access violation writing 0x0000000000000030
Set --print-stacktraces to see the entire traceback
Traceback (most recent call last):
  File "plaidbench.py", line 362, in <module>
    main()
  File "plaidbench.py", line 291, in main
    compile_stop_watch, epochs, stop_watch, output, network)
  File "plaidbench.py", line 107, in train
    model.train_on_batch(x_train[0:batch_size], y_train[0:batch_size])
  File "C:\Python36\lib\site-packages\keras\engine\training.py", line 1762, in train_on_batch
    outputs = self.train_function(ins)
  File "C:\Python36\lib\site-packages\plaidml\keras\backend.py", line 998, in __call__
    self._invoker.invoke()
  File "C:\Python36\lib\site-packages\plaidml\__init__.py", line 1400, in invoke
    return Invocation(self._ctx, self)
  File "C:\Python36\lib\site-packages\plaidml\__init__.py", line 1406, in __init__
    self._as_parameter_ = _lib().plaidml_schedule_invocation(ctx, invoker)
OSError: exception: access violation writing 0x0000000000000030
